# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5b7045ddd223e8da339e258d1c3eb116"
name = "Kizzy Tiered Discount"
application_url = "https://kizzy-tiered-discount.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://kizzy-tiered-discount.onrender.com/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
